#!/usr/bin/env python3
"""
Generate TFA case configuration and emit a shared header/JSON for host/kernel build.

Usage examples:
  python3 generate_cases.py --cases "128,128,1024,128,128" \
      --cases "128,512,2048,128,128"

Each --cases entry format: HEAD_SIZE,S0,S1,CUBE_S0,CUBE_S1
Defaults replicate the previous hard-coded set if --cases is omitted.
"""
import argparse
import json
import os
from pathlib import Path
from typing import List, Dict

DEFAULT_CASES = [
    (128, 128, 1024, 128, 128),
    (128, 128, 2048, 128, 128),
    (128, 128, 8192, 128, 128),
    (128, 512, 1024, 128, 128),
    (128, 512, 2048, 128, 128),
    (128, 512, 8192, 128, 128),
]


def _parse_case_entry(raw: str) -> Dict[str, int]:
    parts = [p.strip() for p in raw.split(',') if p.strip()]
    if len(parts) != 5:
        raise ValueError(f"Expected 5 comma-separated values (HEAD_SIZE,S0,S1,CUBE_S0,CUBE_S1), got '{raw}'")
    head, s0, s1, cube_s0, cube_s1 = map(int, parts)
    return {
        "head_size": head,
        "s0": s0,
        "s1": s1,
        "cube_s0": cube_s0,
        "cube_s1": cube_s1,
    }


def _default_cases() -> List[Dict[str, int]]:
    return [
        {
            "head_size": head,
            "s0": s0,
            "s1": s1,
            "cube_s0": cube_s0,
            "cube_s1": cube_s1,
        }
        for (head, s0, s1, cube_s0, cube_s1) in DEFAULT_CASES
    ]


def _case_name(case: Dict[str, int]) -> str:
    return f"case_float_H_{case['head_size']}_S0_{case['s0']}_S1_{case['s1']}"


def _normalize_case(case: Dict[str, int]) -> Dict[str, int]:
    # Ensure cube_s0 does not exceed s0 and divides evenly; otherwise set cube_s0 = s0
    if case["cube_s0"] > case["s0"] or case["s0"] % case["cube_s0"] != 0:
        case["cube_s0"] = case["s0"]

    # Ensure cube_s1 does not exceed s1 and divides evenly; otherwise set cube_s1 = s1
    if case["cube_s1"] > case["s1"] or case["s1"] % case["cube_s1"] != 0:
        case["cube_s1"] = case["s1"]

    return case


def _render_macro(cases: List[Dict[str, int]]) -> str:
    lines = ["#define TFA_FOR_EACH_CASE(MACRO) \\"]
    for idx, case in enumerate(cases):
        suffix = " \\" if idx + 1 != len(cases) else ""
        line = f"    MACRO({case['s0']}, {case['head_size']}, {case['s1']}, {case['cube_s0']}, {case['cube_s1']}){suffix}"
        lines.append(line)
    return "\n".join(lines)


def _render_header(cases: List[Dict[str, int]]) -> str:
    macro_block = _render_macro(cases)
    array_entries = []
    for case in cases:
        array_entries.append(
            "    {" + ", ".join(
                [
                    str(case["s0"]),
                    str(case["head_size"]),
                    str(case["s1"]),
                    str(case["cube_s0"]),
                    str(case["cube_s1"]),
                    f'"{_case_name(case)}"',
                ]
            ) + "}"
        )
    array_block = ",\n".join(array_entries)

    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off
#include <cstddef>

{macro_block}

struct GeneratedTfaCase {{
    int s0;
    int head_size;
    int s1;
    int cube_s0;
    int cube_s1;
    const char *name;
}};

static constexpr GeneratedTfaCase kGeneratedTfaCases[] = {{
{array_block}
}};
static constexpr std::size_t kGeneratedTfaCasesCount = sizeof(kGeneratedTfaCases) / sizeof(kGeneratedTfaCases[0]);
// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate TFA case header/JSON")
    parser.add_argument(
        "--cases",
        action="append",
        default=None,
        help="Case entry in the format HEAD_SIZE,S0,S1,CUBE_S0,CUBE_S1 (repeat for multiple entries)",
    )
    parser.add_argument(
        "--output-header",
        default=str((Path(__file__).resolve().parent.parent / "build" / "generated_cases.h")),
        help="Output header path (default: kernels/fa_performance/build/generated_cases.h)",
    )
    parser.add_argument(
        "--output-json",
        default=str((Path(__file__).resolve().parent.parent / "build" / "generated_cases.json")),
        help="Output JSON path (default: kernels/fa_performance/build/generated_cases.json)",
    )
    args = parser.parse_args()

    if args.cases:
        cases = [_normalize_case(_parse_case_entry(entry)) for entry in args.cases]
    else:
        cases = [_normalize_case(case) for case in _default_cases()]

    header_text = _render_header(cases)
    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(header_text)

    json_payload = [
        {
            "name": _case_name(case),
            **case,
        }
        for case in cases
    ]
    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(json_payload, indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    print("[INFO] Cases generated:")
    for case in json_payload:
        print(f"  - {case['name']} (H={case['head_size']}, S0={case['s0']}, S1={case['s1']}, CUBE_S0={case['cube_s0']}, CUBE_S1={case['cube_s1']})")


if __name__ == "__main__":
    main()
